columns:
  gender: object
  race_ethnicity: object
  parental_level_of_education: object
  lunch: object
  test_preparation_course: object
  math_score: int64
  reading_score: int64
  writing_score: int64
required_columns:
- gender
- race_ethnicity
- parental_level_of_education
- lunch
- test_preparation_course
- math_score
- reading_score
- writing_score
categorical_columns:
- gender
- race_ethnicity
- parental_level_of_education
- lunch
- test_preparation_course
numerical_columns:
- math_score
- reading_score
- writing_score
